In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [ ]:
size = 5
x = np.arange(1, size+1)
a = np.arange(size)
b = np.arange(size)
c = np.arange(size)

total_width, n = 0.8, 3
width = total_width / n
x = x - (total_width - width) / 2

plt.bar(x, a,  width=width, label='a')
plt.bar(x + width, b, width=width, label='b')
plt.bar(x + 2 * width, c, width=width, label='c')

plt.tick_params(axis='x',length=0)
plt.legend()
plt.show()

In [ ]:
import pandas as pd
import matplotlib.pyplot as plt

df = pd.DataFrame([
                    [1,30,69,70],
                    [2,24,106,80],
                    [3,25,64,120],
                    [4,23,46,25],
                    [5,35,28,86]
                   ],
                  columns=['date', 'guangzhou', 'beijing','shanghai'])

# print(df)
# x = df['date']
# y = df['guangzhou']
# # 绘制柱状图
# plt.bar(x,y,width=0.5,color='C0',edgecolor='grey')

# # 添加x,y轴名称和y轴范围
# plt.ylim(0,40)
# plt.xlabel('2022年',fontsize=11,labelpad=8)
# plt.ylabel('AQI',fontsize=11,labelpad=8)

# # 隐藏x轴刻度线
# plt.tick_params(axis='x',length=0)

# plt.tight_layout()
# plt.savefig('./bar1.png',dpi=600)
# plt.show()

x = df['date']
y1 = df['beijing']
y2 = df['guangzhou']
y3 = df['shanghai']

total_width, n = 0.8, 3
width = total_width / n
x = x - (total_width - width) / 2

plt.bar(x, y1,  width=width, label='beijing')
plt.bar(x + width, y2, width=width, label='guangzhou')
plt.bar(x + 2 * width, y3, width=width, label='shanghai')
plt.legend()
plt.show()

In [ ]:
x = np.arange(0,len(df['date'])*2,2)
width=0.5
x1 = x-width/2
x2 = x+width/2
y1 = df['beijing']
y2 = df['guangzhou']

# 绘制分组柱状图

plt.bar(x1,y1,width=0.5,label='beijing',color='#f9766e',edgecolor='k',zorder=2)
plt.bar(x2,y2,width=0.5,label='guangzhou',color='#00bfc4',edgecolor='k',zorder=2)

# 添加x,y轴名称、图例和网格线
plt.xlabel('2022',fontsize=11)
plt.ylabel('AQI',fontsize=11)
plt.legend(frameon=False)
# plt.grid(ls='--',alpha=0.8)

# 修改x刻度标签为对应日期
plt.xticks(x,df['date'],fontsize=10)
plt.tick_params(axis='x',length=0)

plt.tight_layout()
plt.savefig('./bar2.png',dpi=600)
plt.show()

In [ ]:
from glob import glob

files = glob("./results/*.csv")

In [ ]:
sorted(files)

In [ ]:
import dask.dataframe as dd
import pandas as pd

In [ ]:
# data_df = pd.read_csv(file)
dd_df = dd.read_pickle('/nfs/datasets/cxj/retrievability_bias/categoried/rtrDf_91600_scored.pkl')

In [ ]:
import pickle as pkl
import pandas as pd
data_dir = '/nfs/datasets/cxj/retrievability-bias/categoried'
# data_dir='/root/retrievability-bias'

# with open(f"{data_dir}/rtrDf_101092_scored.pkl", "rb") as f:
#     file = pkl.load(f)
    
# df = pd.DataFrame(file)
# df.to_csv(f"{data_dir}/rtrDf_101092_scored.csv")

In [ ]:
df2 = pd.read_pickle(f"{data_dir}/rtrDf_101092.pkl")

In [ ]:
type(df2)

In [ ]:
df2 =  pd.read_csv(f"{data_dir}/rtrDf_101092_scored.csv")
df2

In [ ]:
# import datatable as dt
# dt_df = dt.Frame(df)
# dt_df.to_csv(f"{data_dir}/rtrDf_101092_scored.csv")

In [ ]:
import torch
gpu_id = torch.cuda.current_device()
print("Current GPU ID:", gpu_id)

In [ ]:
max_split = torch.cuda.get_allocator_max_split_size_mb()
print(f"Current max_split_size_mb: {max_split} MB")

In [ ]:
!pip install pandas

In [ ]:

import glob
resdf = pd.DataFrame(None,columns=['qid','docid','rank'])
for file in glob.glob('/nfs/datasets/cxj/retrievability-bias/categoried/filtered/*.csv'):
    df = pd.read_csv(file)
    read = pd.concat([resdf,df],ignore_index=True)

print(resdf.head(2))

In [13]:
df = pd.read_csv('/nfs/datasets/cxj/retrievability-bias/categoried/rtrDf_79800_scored.csv')

In [14]:
df.head()

,qid,query,docid,query_toks,query_embs,score,docno,rank
0,1040091,what is the easiest way to transfer data from ...,491,"tensor([ 101, 1, 2054, 2003, 1996, 255...","tensor([[ 0.0256, -0.0847, -0.0599, ..., 0.1...",8.290022,491,12564
1,1040091,what is the easiest way to transfer data from ...,1905,"tensor([ 101, 1, 2054, 2003, 1996, 255...","tensor([[ 0.0256, -0.0847, -0.0599, ..., 0.1...",11.873779,1905,9634
2,1040091,what is the easiest way to transfer data from ...,3865,"tensor([ 101, 1, 2054, 2003, 1996, 255...","tensor([[ 0.0256, -0.0847, -0.0599, ..., 0.1...",7.959890,3865,12674
3,1040091,what is the easiest way to transfer data from ...,4398,"tensor([ 101, 1, 2054, 2003, 1996, 255...","tensor([[ 0.0256, -0.0847, -0.0599, ..., 0.1...",14.976305,4398,3593
4,1040091,what is the easiest way to transfer data from ...,4404,"tensor([ 101, 1, 2054, 2003, 1996, 255...","tensor([[ 0.0256, -0.0847, -0.0599, ..., 0.1...",14.434974,4404,4671

In [18]:
grouped  = df.groupby('qid')

In [20]:
rows = grouped.get_group(1040091)

In [21]:
rows

,qid,query,docid,query_toks,query_embs,score,docno,rank
0,1040091,what is the easiest way to transfer data from ...,491,"tensor([ 101, 1, 2054, 2003, 1996, 255...","tensor([[ 0.0256, -0.0847, -0.0599, ..., 0.1...",8.290022,491,12564
1,1040091,what is the easiest way to transfer data from ...,1905,"tensor([ 101, 1, 2054, 2003, 1996, 255...","tensor([[ 0.0256, -0.0847, -0.0599, ..., 0.1...",11.873779,1905,9634
2,1040091,what is the easiest way to transfer data from ...,3865,"tensor([ 101, 1, 2054, 2003, 1996, 255...","tensor([[ 0.0256, -0.0847, -0.0599, ..., 0.1...",7.959890,3865,12674
3,1040091,what is the easiest way to transfer data from ...,4398,"tensor([ 101, 1, 2054, 2003, 1996, 255...","tensor([[ 0.0256, -0.0847, -0.0599, ..., 0.1...",14.976305,4398,3593
4,1040091,what is the easiest way to transfer data from ...,4404,"tensor([ 101, 1, 2054, 2003, 1996, 255...","tensor([[ 0.0256, -0.0847, -0.0599, ..., 0.1...",14.434974,4404,4671
...,...,...,...,...,...,...,...,...
12979,1040091,what is the easiest way to transfer data from ...,8840840,"tensor([ 101, 1, 2054, 2003, 1996, 255...","tensor([[ 0.0256, -0.0847, -0.0599, ..., 0.1...",16.024323,8840840,2063
12980,1040091,what is the easiest way to transfer data from ...,8841034,"tensor([ 101, 1, 2054, 2003, 1996, 255...","tensor([[ 0.0256, -0.0847, -0.0599, ..., 0.1...",14.944291,8841034,3655
12981,1040091,what is the easiest way to transfer data from ...,8841037,"tensor([ 101, 1, 2054, 2003, 1996, 255...","tensor([[ 0.0256, -0.0847, -0.0599, ..., 0.1...",13.735353,8841037,6111
12982,1040091,what is the easiest way to transfer data from ...,8841236,"tensor([ 101, 1, 2054, 2003, 1996, 255...","tensor([[ 0.0256, -0.0847, -0.0599, ..., 0.1...",11.054773,8841236,10691
12983,1040091,what is the easiest way to transfer data from ...,8841725,"tensor([ 101, 1, 2054, 2003, 1996, 255...","tensor([[ 0.0256, -0.0847, -0.0599, ..., 0.1...",13.885210,8841725,5790